PRAGMA foreign_keys = ON;

-- 1) ZIPCODE_INFO
CREATE TABLE ZIPCODE_INFO (
    ZIP_CODE TEXT PRIMARY KEY,
    CITY TEXT NOT NULL,
    STATE TEXT NOT NULL
);

-- 2) INSTRUCTOR_INFO
CREATE TABLE INSTRUCTOR_INFO (
    INSTRUCTOR_ID INTEGER PRIMARY KEY,
    INSTRUCTOR_FIRST_NAME TEXT NOT NULL,
    INSTRUCTOR_LAST_NAME TEXT NOT NULL,
    STREET_ADDRESS TEXT,
    ZIP_CODE TEXT,
    FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE)
);

-- 3) COURSE_INFO
CREATE TABLE COURSE_INFO (
    COURSE_NO INTEGER PRIMARY KEY,
    COURSE_NAME TEXT NOT NULL,
    COURSE_PREREQUISITE INTEGER,
    COST REAL NOT NULL
);

-- 4) STUDENT_INFO
CREATE TABLE STUDENT_INFO (
    STUDENT_ID INTEGER PRIMARY KEY,
    STUDENT_FIRST_NAME TEXT NOT NULL,
    STUDENT_LAST_NAME TEXT NOT NULL,
    STREET_ADDRESS TEXT,
    ZIP_CODE TEXT,
    FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE)
);

-- 5) SECTION_INFO
CREATE TABLE SECTION_INFO (
    SECTION_ID INTEGER PRIMARY KEY,
    COURSE_NO INTEGER,
    SECTION_NO INTEGER NOT NULL,
    INSTRUCTOR_ID INTEGER,
    LOCATION TEXT,
    CAPACITY INTEGER,
    FOREIGN KEY (COURSE_NO) REFERENCES COURSE_INFO(COURSE_NO),
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID)
);

-- 6) ENROLLMENT_INFO
CREATE TABLE ENROLLMENT_INFO (
    STUDENT_ID INTEGER,
    SECTION_ID INTEGER,
    ENROLLMENT_DATE TEXT,
    PRIMARY KEY (STUDENT_ID, SECTION_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID)
);

-- 7) GRADE_INFO
CREATE TABLE GRADE_INFO (
    STUDENT_ID INTEGER,
    SECTION_ID INTEGER,
    GRADE_TYPE_CODE TEXT CHECK (GRADE_TYPE_CODE IN ('FI','HM','MT','PA','PJ','QZ')),
    GRADE_CODE_OCCURANCE INTEGER,
    NUMERIC_GRADE INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID)
);


INSERT INTO ZIPCODE_INFO VALUES ('56001','Bangalore','KA');

INSERT INTO COURSE_INFO VALUES (101,'C# Basics',NULL,5000);

INSERT INTO INSTRUCTOR_INFO VALUES (1,'Ravi','Kumar','MG Road','56001');

INSERT INTO STUDENT_INFO VALUES (10,'Anu','Sharma','BTM Layout','56001');

INSERT INTO SECTION_INFO VALUES (1001,101,1,1,'Room A',30);

INSERT INTO ENROLLMENT_INFO VALUES (10,1001,'2025-02-04');

INSERT INTO GRADE_INFO(STUDENT_ID,SECTION_ID,GRADE_TYPE_CODE,GRADE_CODE_OCCURANCE) VALUES (10,1001,'FI',1);

INSERT INTO ZIPCODE_INFO VALUES ('56002',NULL,'KA');
--should fail 

INSERT INTO STUDENT_INFO VALUES (11,'Raj','Verma','HSR','99999');
--Should fail (ZIP not present). 

INSERT INTO GRADE_INFO VALUES (10,1001,'XX',1,50);
--fail 

INSERT INTO ZIPCODE_INFO VALUES ('56001','City','KA');
--fail 

SELECT * FROM GRADE_INFO;
SELECT * FROM ENROLLMENT_INFO;


















